[package]
name = "nested-star-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
nested-sta-rs = { git = "ssh://git@github.com/brave-experiments/nested-sta-rs", branch = "main" }
sta-rs = { git = "https://github.com/brave/sta-rs", branch = "main" }
actix-web = "4"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1.17", features = ["full"] }
futures = "0.3"
futures-core = "0.3"
dotenv = "0.15"
derive_more = "0.99"
hex = "0.4"
rand = "0.8"
clap = { version = "3.1", features = ["derive"] }
base64 = "0.13"
bincode = "1.3"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
rdkafka = "0.28"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
r2d2 = "0.8"
chrono = "0.4"
tokio-util = "0.7"
reqwest = { version = "0.11", features = ["json"] }
rusoto_core = "0.47"
rusoto_s3 = "0.47"

[profile.dev]
opt-level = 3
