[package]
name = "constellation-processors"
version = "1.0.0"
edition = "2021"

[dependencies]
star-constellation = { git = "https://github.com/brave/constellation", rev = "6c91f94d7b307f7dec08e1a86edcbf789d420185" }
sta-rs = { git = "https://github.com/brave/sta-rs" }
actix-web = "4"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.26", features = ["full"] }
futures = "0.3"
futures-core = "0.3"
dotenv = "0.15"
derive_more = "0.99"
hex = "0.4"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
base64 = "0.20"
bincode = "1.3"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
rdkafka = { version = "0.29", features = ["ssl"] }
diesel = { version = "2.0", features = ["postgres", "r2d2"] }
diesel_migrations = "2.0"
r2d2 = "0.8"
chrono = "0.4"
tokio-util = "0.7"
reqwest = { version = "0.11", features = ["json"] }
rusoto_core = "0.48"
rusoto_s3 = "0.48"
rusoto_credential = "0.48"
rusoto_sts = "0.48"
prometheus-client = "0.18"
sentry = "0.30"
jemallocator = "0.5"

[profile.dev]
opt-level = 3
