version: '3.9'

networks:
  star-agg:

services:
  localstack:
    image: localstack/localstack@sha256:aa323588b75dfb4073ad3dd2b24671b2299de3ea293c9e22256f63db9ab2ac69
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./misc/create_localstack_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh"
    networks:
      - star-agg
  db:
    image: postgres@sha256:f58300ac8d393b2e3b09d36ea12d7d24ee9440440e421472a300e929ddb63460
    command: postgres -c 'max_connections=300'
    ports:
      - 5642:5432
    environment:
      POSTGRES_USER: star
      POSTGRES_PASSWORD: password
    networks:
      - star-agg
    volumes:
      - "./misc/create_additional_dbs.sql:/docker-entrypoint-initdb.d/create_additional_dbs.sql"

  zookeeper:
    image: bitnami/zookeeper@sha256:a1f45921c809f3f39050a79a5a97fbd625ae0ad6f93633b6172db69386b9176e
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - star-agg
  kafka:
    image: bitnami/kafka@sha256:5f0ed16902daa9797f5cc22d872e6e40aac729df031ee1db32ddbb74133faa4c
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=4
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_TRANSACTION_MAX_TIMEOUT_MS=3600000
    depends_on:
      - zookeeper
    networks:
      - star-agg
    volumes:
      - kafka-data:/bitnami/kafka
volumes:
  kafka-data:
