version: '3.9'

networks:
  star-agg:

services:
  localstack:
    image: localstack/localstack@sha256:2ad9d59fad4df84e348e4a0c0ce1e2e12526495b650b1ca2b723f7d6efcf3e7d
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./misc/create_localstack_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh"
    networks:
      - star-agg
  db:
    image: postgres@sha256:6b841c8f6a819884207402f1209a8116844365df15fca8cf556fc54a24c70800
    command: postgres -c 'max_connections=300'
    ports:
      - 5642:5432
    environment:
      POSTGRES_USER: star
      POSTGRES_PASSWORD: password
    networks:
      - star-agg
    volumes:
      - "./misc/create_additional_dbs.sql:/docker-entrypoint-initdb.d/create_additional_dbs.sql"

  zookeeper:
    image: bitnami/zookeeper@sha256:7a596fb96f394d6b22b20cd46fc33af7be80a38749c873688bdd16724373c7a7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - star-agg
  kafka:
    image: bitnami/kafka@sha256:dd3beae321134d2601c37a28dadfb421b4576666c56cce22688f8b2ce702aeb0
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=4
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_TRANSACTION_MAX_TIMEOUT_MS=3600000
    depends_on:
      - zookeeper
    networks:
      - star-agg
    volumes:
      - kafka-data:/bitnami/kafka
volumes:
  kafka-data:
