version: '3.9'

networks:
  star-agg:

services:
  localstack:
    image: localstack/localstack@sha256:af260c3467fee9fcfa6cae4830952bea14da4dd1337eeb662d9df7064a03447c
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./misc/create_localstack_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh"
    networks:
      - star-agg
  db:
    image: postgres@sha256:e8199d2b15fd88c1b0b6f07c4eab878059ec724c44b0fcba3d6f7c83ff1e6ba6
    command: postgres -c 'max_connections=300'
    ports:
      - 5642:5432
    environment:
      POSTGRES_USER: star
      POSTGRES_PASSWORD: password
    networks:
      - star-agg
    volumes:
      - "./misc/create_additional_dbs.sql:/docker-entrypoint-initdb.d/create_additional_dbs.sql"

  zookeeper:
    image: bitnami/zookeeper@sha256:470a36ecb92805bfee35d20d2cfdfc6be220c232cce0d80911cad83ea6c78e26
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - star-agg
  kafka:
    image: bitnami/kafka@sha256:25e33405c88edb664ab049fc9a351b0ef700eb6df070066be53a2a676d8d1b86
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=4
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_TRANSACTION_MAX_TIMEOUT_MS=3600000
    depends_on:
      - zookeeper
    networks:
      - star-agg
    volumes:
      - kafka-data:/bitnami/kafka
volumes:
  kafka-data:
