version: '3.9'

networks:
  star-agg:

services:
  localstack:
    image: localstack/localstack@sha256:b5c082a6d78d49fc4a102841648a8adeab4895f7d9a4ad042d7d485aed2da10d
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./misc/create_localstack_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh"
    networks:
      - star-agg
  db:
    image: postgres@sha256:6b841c8f6a819884207402f1209a8116844365df15fca8cf556fc54a24c70800
    command: postgres -c 'max_connections=300'
    ports:
      - 5642:5432
    environment:
      POSTGRES_USER: star
      POSTGRES_PASSWORD: password
    networks:
      - star-agg
    volumes:
      - "./misc/create_additional_dbs.sql:/docker-entrypoint-initdb.d/create_additional_dbs.sql"

  zookeeper:
    image: bitnami/zookeeper@sha256:24c0cf6372add746789caf4baee97d6e1605be3be522cd1ddb04206fc9a1c901
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - star-agg
  kafka:
    image: bitnami/kafka@sha256:c1e54c8bc46edfc23c25d53f6de1b1433e2e919870c679fa7a846a8af0b03427
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=4
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_TRANSACTION_MAX_TIMEOUT_MS=3600000
    depends_on:
      - zookeeper
    networks:
      - star-agg
    volumes:
      - kafka-data:/bitnami/kafka
volumes:
  kafka-data:
