[package]
name = "test-client"
version = "0.1.0"
edition = "2021"

[dependencies]
nested-sta-rs = { git = "https://github.com/brave-experiments/nested-sta-rs", branch = "main" }
base64 = "0.13"
rand = "0.8"
clap = { version = "3.1", features = ["derive"] }
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
csv = "1.1"

[profile.dev]
opt-level = 3
