on:
  push:
  pull_request:

name: Checks

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    services:
      postgres:
        image: postgres@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
        env:
          POSTGRES_USER: star
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          components: clippy, rustfmt
          toolchain: 1.78
          override: true

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Format
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: fmt
          args: --check

      - name: Install diesel
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: install
          args: --force diesel_cli

      - name: Run db migration
        run: diesel migration run
        env:
          DATABASE_URL: "postgres://star:password@localhost:5432/postgres"
      - name: Build/Test
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: test
        env:
          TEST_DATABASE_URL: "postgres://star:password@localhost:5432/postgres"

      - name: Test Client Format
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: fmt
          args: --check --manifest-path misc/test-client/Cargo.toml

      - name: Test Client Build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: --release --all-targets --manifest-path misc/test-client/Cargo.toml
